from . import account_move
from . import company
from . import event
from . import hr_employee_siat
from . import invoice_cancellation_by_cuf
from . import invoice_item
from . import invoice
from . import ir_menu
from . import mail_template
from . import package
from . import pos_config
from . import pos_order
from . import pos_payment
from . import product
from . import report_invoice
from . import res_config_settings
from . import res_partner
from . import res_users
from . import siat_activity
from . import siat_branch
from . import siat_cancellation_reason
from . import siat_country
from . import siat_cufd_code
from . import siat_cuis_code
from . import siat_currency_type
from . import siat_document_sector
from . import siat_emission_type
from . import siat_employee_pos
from . import siat_identity_document
from . import siat_invoice_label
from . import siat_invoice_type
from . import siat_invoicer
from . import siat_measure_unit
from . import siat_payment_type
from . import siat_point_of_sale
from . import siat_pos_type
from . import siat_product_homologation
from . import siat_product_service
from . import siat_room_type
from . import siat_service_message
from . import siat_significant_event
from . import siat_type_document_sector
from . import siat_utils