# -*- coding: utf-8 -*-
{
    'name': "Facturación SIAT",
    'summary': "Módulo de facturación SIAT BOLIVIA",
    'description': """Módulo de Facturación de acuerdo a la normativa boliviana de impuestos""",
    'author': "ONIXIA S.R.L.",
    'website': "",
    'category': 'Onixia/Onixia',
    'version': '2.0',
	'depends': ['base', 'account', 'hr', 'web', 'stock', 'stock_account', 'mail', 'point_of_sale', 'pos_sale'],

    'data': [
        'security/siat_groups.xml',
        'security/ir.model.access.csv',
        'security/ir.rule.xml',
        'views/siat_countries.xml',
        'views/siat_cancellation_reasons.xml',
        'views/siat_activities.xml',
        'views/siat_currency_types.xml',
        'views/siat_document_sector.xml',
        'views/siat_emission_types.xml',
        'views/siat_identity_documents.xml',
        'views/siat_invoice_labels.xml',
        'views/siat_invoice_types.xml',
        'views/siat_product_service.xml',
        'views/siat_room_type.xml',
        'views/siat_service_messages.xml',
        'views/siat_significant_events.xml',
        'views/siat_type_document_sector.xml',
        'views/siat_measure_units.xml',
        'views/siat_pos_types.xml',
        'views/siat_payment_methods.xml',
        'views/siat_pos_cuis.xml',
        'views/siat_cufd.xml',
        'views/siat_branch.xml',

        'views/actions/siat_actions.xml',
        'views/menus/siat_menu.xml',
        'views/updated_views/product_view.xml',
        'views/updated_views/res_config_settings_views.xml',
        'views/updated_views/res_partner.xml',
        'views/updated_views/pos_config.xml',
        'views/updated_views/account_move_siat.xml',
        'views/invoice_email_template.xml',
        'views/invoice_cancellation_template.xml',
        'views/invoice_cancellation_by_cuf.xml',
        'views/siat_invoice_list.xml',
        'views/siat_event.xml',
        'data/default_data.xml',
        'data/cron_jobs.xml',

        'report/report_invoice.xml',
        'views/updated_views/account_move_event_fields.xml',
        'views/siat_invoicer_form.xml',
        'views/updated_views/res_users.xml',
        'views/user_pos_config.xml',
        'views/updated_views/pos_order_view.xml',
        'views/updated_views/res_company_views.xml',
        'views/updated_views/view_employee_form.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'siat_module/static/src/overrides/models/order.js',
            'siat_module/static/src/overrides/components/payment_screen/payment_screen.js',
            'siat_module/static/src/overrides/components/receipt_screen/receipt_screen.js',
            'siat_module/static/src/xml/pos_product_screen_button.xml',
            'siat_module/static/src/xml/receipt_screen.xml',
        ],
        'web.assets_backend': [
            'siat_module/static/src/js/invoice_add_button.js',
            'siat_module/static/src/js/sync_menu_buttons.js',
            'siat_module/static/src/xml/invoice_add_button.xml',
            'siat_module/static/src/xml/sync_menu_buttons.xml',
            'siat_module/static/src/components/**/*',
        ],
    },
    'module_type': 'official',
    'images': ['static/description/icon.png'],
    'installable': True,
	'application': True,
	'license': 'LGPL-3',

    'uninstall_hook': 'pre_uninstall_hook',

}

